name: CI
on:
  push: { branches: [main] }
  pull_request: null
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Build Sphinx Documentation
        run: ./scripts/html.sh
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/html
  deploy:
    permissions:
      id-token: write
      pages: write
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/deploy-pages@v4
        id: deployment
